"""Result summary -- aggregate one run's results_*.json into a readable report.

- tally findings by severity
- group tools by CLS test category (PS/FW/CO/CP/MA/AU/...) with their findings
- collect a "manual follow-up / incomplete" list (skipped / manual / failed)
- output: terminal summary + a Markdown file (results/summary_<stamp>.md)

That Markdown is the handoff from Part 1 (run tools, get data) to Part 2 (AI fills
the CLS template and drafts the report): it is already organized by CLS category,
so the AI just reads it + the template to draft provision conclusions.

All output is ASCII-only so it renders on any terminal (including a Kali box with
no CJK font).
"""
from __future__ import annotations

import glob
import json
from datetime import datetime
from pathlib import Path
from typing import List, Optional

ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = ROOT / "results"

SEV_ORDER = ["critical", "high", "medium", "low", "info"]
SEV_LABEL = {
    "critical": "Critical", "high": "High", "medium": "Medium",
    "low": "Low", "info": "Info",
}

CAT_NAMES = {
    "PS": "Ports and Services",
    "FW": "Firmware",
    "FWU": "Firmware Updates",
    "CO": "Communications",
    "CP": "Configuration Portal",
    "MA": "Mobile Application",
    "AU": "Authentication",
    "AWR": "Wireless Router",
    "OA": "Other Attacks",
    "HW": "Hardware",
}
CAT_ORDER = list(CAT_NAMES.keys())

# status grouping
_SKIPPED = {"skipped-no-binary", "skipped-missing-fields"}
_FAILED = {"error", "timeout", "missing-binary"}


def latest_results(results_dir: Path = RESULTS_DIR) -> Optional[Path]:
    """Return the newest results_*.json in results/ (timestamped name sorts fine)."""
    files = sorted(glob.glob(str(results_dir / "results_*.json")))
    return Path(files[-1]) if files else None


def load(path: Path) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _category(result: dict) -> str:
    cat = (result.get("category") or "").strip()
    if cat:
        return cat
    test = result.get("test", "")
    return (test.split("-")[0].split("/")[0] or "?").strip() or "?"


def _sev(finding: dict) -> str:
    sev = str(finding.get("severity", "info")).lower()
    return sev if sev in SEV_LABEL else "info"


def build_summary(report: dict) -> dict:
    results: List[dict] = report.get("results", [])

    sev_counts = {s: 0 for s in SEV_ORDER}
    status_counts = {"ran": 0, "skipped": 0, "manual": 0, "failed": 0}
    follow_up: List[dict] = []

    for r in results:
        status = r.get("status", "")
        if status == "manual":
            status_counts["manual"] += 1
            follow_up.append(r)
        elif status in _SKIPPED:
            status_counts["skipped"] += 1
            follow_up.append(r)
        elif status in _FAILED:
            status_counts["failed"] += 1
            follow_up.append(r)
        else:  # done
            status_counts["ran"] += 1

        for f in r.get("findings", []):
            sev_counts[_sev(f)] += 1

    # group by category (preserve order)
    by_cat: dict[str, List[dict]] = {}
    for r in results:
        by_cat.setdefault(_category(r), []).append(r)

    return {
        "sev_counts": sev_counts,
        "status_counts": status_counts,
        "total_findings": sum(sev_counts.values()),
        "by_cat": by_cat,
        "follow_up": follow_up,
        "n_tools": len(results),
    }


def _ordered_cats(by_cat: dict) -> List[str]:
    known = [c for c in CAT_ORDER if c in by_cat]
    extra = sorted(c for c in by_cat if c not in CAT_ORDER)
    return known + extra


def _status_en(status: str) -> str:
    return {
        "done": "ran", "manual": "manual TODO", "error": "failed",
        "timeout": "timeout", "missing-binary": "missing binary",
        "skipped-no-binary": "skipped (not installed)",
        "skipped-missing-fields": "skipped (missing fields)",
    }.get(status, status or "?")


def render_markdown(report: dict, summary: dict, source: str) -> str:
    dut = report.get("dut", {})
    name = dut.get("toe_name", "?")
    sc = summary["status_counts"]
    lines: List[str] = []

    lines.append(f"# CLS Test Result Summary - {name}")
    lines.append("")
    lines.append("> Auto-generated by `cls.py report`; input for manual review + Part 2 "
                 "(AI fills the CLS template and drafts the report).")
    lines.append("> Findings are the tools' machine first-pass only; "
                 "**final PASS/FAIL/NA verdicts need assessor review**.")
    lines.append("")
    lines.append(f"- **DUT**: {name}"
                 + (f" ({dut.get('model')})" if dut.get("model") else "")
                 + f" @ {dut.get('ip', '?')}")
    lines.append(f"- **Generated**: {report.get('generated_at', '?')}")
    lines.append(f"- **Result file**: `{source}`")
    lines.append(f"- **Modules**: {summary['n_tools']} total "
                 f"(ran {sc['ran']}, skipped {sc['skipped']}, manual {sc['manual']}, failed {sc['failed']})")
    lines.append("")

    # severity breakdown
    lines.append("## Severity Breakdown")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---:|")
    for s in SEV_ORDER:
        lines.append(f"| {SEV_LABEL[s]} | {summary['sev_counts'][s]} |")
    lines.append(f"| **Total** | **{summary['total_findings']}** |")
    lines.append("")

    # by category
    lines.append("## By CLS Test Category")
    lines.append("")
    for cat in _ordered_cats(summary["by_cat"]):
        title = CAT_NAMES.get(cat, cat)
        lines.append(f"### {cat} - {title}")
        lines.append("")
        lines.append("| Tool | Test | Status | Findings |")
        lines.append("|---|---|---|---:|")
        for r in summary["by_cat"][cat]:
            lines.append(
                f"| {r.get('tool', '?')} | {r.get('test', '?')} "
                f"| {_status_en(r.get('status', ''))} | {len(r.get('findings', []))} |"
            )
        lines.append("")
        # detailed findings (per tool, sorted by severity)
        for r in summary["by_cat"][cat]:
            fs = r.get("findings", [])
            if not fs:
                continue
            lines.append(f"**{r.get('tool', '?')}** ({r.get('test', '?')})")
            lines.append("")
            for f in sorted(fs, key=lambda x: SEV_ORDER.index(_sev(x))):
                sev = _sev(f)
                detail = f.get("detail", "")
                lines.append(
                    f"- [{SEV_LABEL[sev]}] "
                    f"{f.get('title', '')}" + (f" - {detail}" if detail else "")
                )
            lines.append("")

    # manual follow-up
    lines.append("## Manual Follow-up / Incomplete")
    lines.append("")
    if not summary["follow_up"]:
        lines.append("(none)")
    else:
        for r in summary["follow_up"]:
            note = r.get("note") or r.get("description") or _status_en(r.get("status", ""))
            lines.append(
                f"- [ ] **{r.get('tool', '?')}** ({r.get('test', '?')}) "
                f"- {_status_en(r.get('status', ''))} - {note}"
            )
    lines.append("")
    return "\n".join(lines)


def render_terminal(report: dict, summary: dict) -> str:
    dut = report.get("dut", {})
    sc = summary["status_counts"]
    out: List[str] = []
    out.append(f"DUT: {dut.get('toe_name', '?')} @ {dut.get('ip', '?')}")
    out.append(f"Modules: {summary['n_tools']} total "
               f"(ran {sc['ran']}, skipped {sc['skipped']}, manual {sc['manual']}, failed {sc['failed']})")
    tally = "  ".join(f"{SEV_LABEL[s]} {summary['sev_counts'][s]}" for s in SEV_ORDER)
    out.append(f"Findings: {summary['total_findings']}  [{tally}]")
    out.append("")
    out.append("By category:")
    for cat in _ordered_cats(summary["by_cat"]):
        rows = summary["by_cat"][cat]
        nfind = sum(len(r.get("findings", [])) for r in rows)
        tools = ", ".join(r.get("tool", "?") for r in rows)
        out.append(f"  {cat:<4} {CAT_NAMES.get(cat, cat):<20} {nfind:>3} findings  ({tools})")
    if summary["follow_up"]:
        out.append("")
        out.append(f"Manual follow-up: {len(summary['follow_up'])} items (see Markdown)")
    return "\n".join(out)


def write_summary_md(report: dict, source: str, results_dir: Path = RESULTS_DIR) -> Path:
    """Build the summary and write the Markdown; return the written path."""
    summary = build_summary(report)
    md = render_markdown(report, summary, source)
    results_dir.mkdir(exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = results_dir / f"summary_{stamp}.md"
    out_path.write_text(md, encoding="utf-8")
    return out_path
